\c musiconnect

INSERT INTO public.country (id, name) VALUES (533, 'Aruba');
INSERT INTO public.country (id, name) VALUES (4, 'Afghanistan');
INSERT INTO public.country (id, name) VALUES (24, 'Angola');
INSERT INTO public.country (id, name) VALUES (660, 'Anguilla');
INSERT INTO public.country (id, name) VALUES (248, 'Åland Islands');
INSERT INTO public.country (id, name) VALUES (8, 'Albania');
INSERT INTO public.country (id, name) VALUES (20, 'Andorra');
INSERT INTO public.country (id, name) VALUES (784, 'United Arab Emirates');
INSERT INTO public.country (id, name) VALUES (32, 'Argentina');
INSERT INTO public.country (id, name) VALUES (51, 'Armenia');
INSERT INTO public.country (id, name) VALUES (16, 'American Samoa');
INSERT INTO public.country (id, name) VALUES (10, 'Antarctica');
INSERT INTO public.country (id, name) VALUES (260, 'French Southern Territories');
INSERT INTO public.country (id, name) VALUES (28, 'Antigua and Barbuda');
INSERT INTO public.country (id, name) VALUES (36, 'Australia');
INSERT INTO public.country (id, name) VALUES (40, 'Austria');
INSERT INTO public.country (id, name) VALUES (31, 'Azerbaijan');
INSERT INTO public.country (id, name) VALUES (108, 'Burundi');
INSERT INTO public.country (id, name) VALUES (56, 'Belgium');
INSERT INTO public.country (id, name) VALUES (204, 'Benin');
INSERT INTO public.country (id, name) VALUES (535, 'Bonaire, Sint Eustatius and Saba');
INSERT INTO public.country (id, name) VALUES (854, 'Burkina Faso');
INSERT INTO public.country (id, name) VALUES (50, 'Bangladesh');
INSERT INTO public.country (id, name) VALUES (100, 'Bulgaria');
INSERT INTO public.country (id, name) VALUES (48, 'Bahrain');
INSERT INTO public.country (id, name) VALUES (44, 'Bahamas');
INSERT INTO public.country (id, name) VALUES (70, 'Bosnia and Herzegovina');
INSERT INTO public.country (id, name) VALUES (652, 'Saint Barthélemy');
INSERT INTO public.country (id, name) VALUES (112, 'Belarus');
INSERT INTO public.country (id, name) VALUES (84, 'Belize');
INSERT INTO public.country (id, name) VALUES (60, 'Bermuda');
INSERT INTO public.country (id, name) VALUES (68, 'Bolivia, Plurinational State of');
INSERT INTO public.country (id, name) VALUES (76, 'Brazil');
INSERT INTO public.country (id, name) VALUES (52, 'Barbados');
INSERT INTO public.country (id, name) VALUES (96, 'Brunei Darussalam');
INSERT INTO public.country (id, name) VALUES (64, 'Bhutan');
INSERT INTO public.country (id, name) VALUES (74, 'Bouvet Island');
INSERT INTO public.country (id, name) VALUES (72, 'Botswana');
INSERT INTO public.country (id, name) VALUES (140, 'Central African Republic');
INSERT INTO public.country (id, name) VALUES (124, 'Canada');
INSERT INTO public.country (id, name) VALUES (166, 'Cocos (Keeling) Islands');
INSERT INTO public.country (id, name) VALUES (756, 'Switzerland');
INSERT INTO public.country (id, name) VALUES (152, 'Chile');
INSERT INTO public.country (id, name) VALUES (156, 'China');
INSERT INTO public.country (id, name) VALUES (384, 'Côte d''Ivoire');
INSERT INTO public.country (id, name) VALUES (120, 'Cameroon');
INSERT INTO public.country (id, name) VALUES (180, 'Congo, The Democratic Republic of the');
INSERT INTO public.country (id, name) VALUES (178, 'Congo');
INSERT INTO public.country (id, name) VALUES (184, 'Cook Islands');
INSERT INTO public.country (id, name) VALUES (170, 'Colombia');
INSERT INTO public.country (id, name) VALUES (174, 'Comoros');
INSERT INTO public.country (id, name) VALUES (132, 'Cabo Verde');
INSERT INTO public.country (id, name) VALUES (188, 'Costa Rica');
INSERT INTO public.country (id, name) VALUES (192, 'Cuba');
INSERT INTO public.country (id, name) VALUES (531, 'Curaçao');
INSERT INTO public.country (id, name) VALUES (162, 'Christmas Island');
INSERT INTO public.country (id, name) VALUES (136, 'Cayman Islands');
INSERT INTO public.country (id, name) VALUES (196, 'Cyprus');
INSERT INTO public.country (id, name) VALUES (203, 'Czechia');
INSERT INTO public.country (id, name) VALUES (276, 'Germany');
INSERT INTO public.country (id, name) VALUES (262, 'Djibouti');
INSERT INTO public.country (id, name) VALUES (212, 'Dominica');
INSERT INTO public.country (id, name) VALUES (208, 'Denmark');
INSERT INTO public.country (id, name) VALUES (214, 'Dominican Republic');
INSERT INTO public.country (id, name) VALUES (12, 'Algeria');
INSERT INTO public.country (id, name) VALUES (218, 'Ecuador');
INSERT INTO public.country (id, name) VALUES (818, 'Egypt');
INSERT INTO public.country (id, name) VALUES (232, 'Eritrea');
INSERT INTO public.country (id, name) VALUES (732, 'Western Sahara');
INSERT INTO public.country (id, name) VALUES (724, 'Spain');
INSERT INTO public.country (id, name) VALUES (233, 'Estonia');
INSERT INTO public.country (id, name) VALUES (231, 'Ethiopia');
INSERT INTO public.country (id, name) VALUES (246, 'Finland');
INSERT INTO public.country (id, name) VALUES (242, 'Fiji');
INSERT INTO public.country (id, name) VALUES (238, 'Falkland Islands (Malvinas)');
INSERT INTO public.country (id, name) VALUES (250, 'France');
INSERT INTO public.country (id, name) VALUES (234, 'Faroe Islands');
INSERT INTO public.country (id, name) VALUES (583, 'Micronesia, Federated States of');
INSERT INTO public.country (id, name) VALUES (266, 'Gabon');
INSERT INTO public.country (id, name) VALUES (826, 'United Kingdom');
INSERT INTO public.country (id, name) VALUES (268, 'Georgia');
INSERT INTO public.country (id, name) VALUES (831, 'Guernsey');
INSERT INTO public.country (id, name) VALUES (288, 'Ghana');
INSERT INTO public.country (id, name) VALUES (292, 'Gibraltar');
INSERT INTO public.country (id, name) VALUES (324, 'Guinea');
INSERT INTO public.country (id, name) VALUES (312, 'Guadeloupe');
INSERT INTO public.country (id, name) VALUES (270, 'Gambia');
INSERT INTO public.country (id, name) VALUES (624, 'Guinea-Bissau');
INSERT INTO public.country (id, name) VALUES (226, 'Equatorial Guinea');
INSERT INTO public.country (id, name) VALUES (300, 'Greece');
INSERT INTO public.country (id, name) VALUES (308, 'Grenada');
INSERT INTO public.country (id, name) VALUES (304, 'Greenland');
INSERT INTO public.country (id, name) VALUES (320, 'Guatemala');
INSERT INTO public.country (id, name) VALUES (254, 'French Guiana');
INSERT INTO public.country (id, name) VALUES (316, 'Guam');
INSERT INTO public.country (id, name) VALUES (328, 'Guyana');
INSERT INTO public.country (id, name) VALUES (344, 'Hong Kong');
INSERT INTO public.country (id, name) VALUES (334, 'Heard Island and McDonald Islands');
INSERT INTO public.country (id, name) VALUES (340, 'Honduras');
INSERT INTO public.country (id, name) VALUES (191, 'Croatia');
INSERT INTO public.country (id, name) VALUES (332, 'Haiti');
INSERT INTO public.country (id, name) VALUES (348, 'Hungary');
INSERT INTO public.country (id, name) VALUES (360, 'Indonesia');
INSERT INTO public.country (id, name) VALUES (833, 'Isle of Man');
INSERT INTO public.country (id, name) VALUES (356, 'India');
INSERT INTO public.country (id, name) VALUES (86, 'British Indian Ocean Territory');
INSERT INTO public.country (id, name) VALUES (372, 'Ireland');
INSERT INTO public.country (id, name) VALUES (364, 'Iran, Islamic Republic of');
INSERT INTO public.country (id, name) VALUES (368, 'Iraq');
INSERT INTO public.country (id, name) VALUES (352, 'Iceland');
INSERT INTO public.country (id, name) VALUES (376, 'Israel');
INSERT INTO public.country (id, name) VALUES (380, 'Italy');
INSERT INTO public.country (id, name) VALUES (388, 'Jamaica');
INSERT INTO public.country (id, name) VALUES (832, 'Jersey');
INSERT INTO public.country (id, name) VALUES (400, 'Jordan');
INSERT INTO public.country (id, name) VALUES (392, 'Japan');
INSERT INTO public.country (id, name) VALUES (398, 'Kazakhstan');
INSERT INTO public.country (id, name) VALUES (404, 'Kenya');
INSERT INTO public.country (id, name) VALUES (417, 'Kyrgyzstan');
INSERT INTO public.country (id, name) VALUES (116, 'Cambodia');
INSERT INTO public.country (id, name) VALUES (296, 'Kiribati');
INSERT INTO public.country (id, name) VALUES (659, 'Saint Kitts and Nevis');
INSERT INTO public.country (id, name) VALUES (410, 'Korea, Republic of');
INSERT INTO public.country (id, name) VALUES (414, 'Kuwait');
INSERT INTO public.country (id, name) VALUES (418, 'Lao People''s Democratic Republic');
INSERT INTO public.country (id, name) VALUES (422, 'Lebanon');
INSERT INTO public.country (id, name) VALUES (430, 'Liberia');
INSERT INTO public.country (id, name) VALUES (434, 'Libya');
INSERT INTO public.country (id, name) VALUES (662, 'Saint Lucia');
INSERT INTO public.country (id, name) VALUES (438, 'Liechtenstein');
INSERT INTO public.country (id, name) VALUES (144, 'Sri Lanka');
INSERT INTO public.country (id, name) VALUES (426, 'Lesotho');
INSERT INTO public.country (id, name) VALUES (440, 'Lithuania');
INSERT INTO public.country (id, name) VALUES (442, 'Luxembourg');
INSERT INTO public.country (id, name) VALUES (428, 'Latvia');
INSERT INTO public.country (id, name) VALUES (446, 'Macao');
INSERT INTO public.country (id, name) VALUES (663, 'Saint Martin (French part)');
INSERT INTO public.country (id, name) VALUES (504, 'Morocco');
INSERT INTO public.country (id, name) VALUES (492, 'Monaco');
INSERT INTO public.country (id, name) VALUES (498, 'Moldova, Republic of');
INSERT INTO public.country (id, name) VALUES (450, 'Madagascar');
INSERT INTO public.country (id, name) VALUES (462, 'Maldives');
INSERT INTO public.country (id, name) VALUES (484, 'Mexico');
INSERT INTO public.country (id, name) VALUES (584, 'Marshall Islands');
INSERT INTO public.country (id, name) VALUES (807, 'North Macedonia');
INSERT INTO public.country (id, name) VALUES (466, 'Mali');
INSERT INTO public.country (id, name) VALUES (470, 'Malta');
INSERT INTO public.country (id, name) VALUES (104, 'Myanmar');
INSERT INTO public.country (id, name) VALUES (499, 'Montenegro');
INSERT INTO public.country (id, name) VALUES (496, 'Mongolia');
INSERT INTO public.country (id, name) VALUES (580, 'Northern Mariana Islands');
INSERT INTO public.country (id, name) VALUES (508, 'Mozambique');
INSERT INTO public.country (id, name) VALUES (478, 'Mauritania');
INSERT INTO public.country (id, name) VALUES (500, 'Montserrat');
INSERT INTO public.country (id, name) VALUES (474, 'Martinique');
INSERT INTO public.country (id, name) VALUES (480, 'Mauritius');
INSERT INTO public.country (id, name) VALUES (454, 'Malawi');
INSERT INTO public.country (id, name) VALUES (458, 'Malaysia');
INSERT INTO public.country (id, name) VALUES (175, 'Mayotte');
INSERT INTO public.country (id, name) VALUES (516, 'Namibia');
INSERT INTO public.country (id, name) VALUES (540, 'New Caledonia');
INSERT INTO public.country (id, name) VALUES (562, 'Niger');
INSERT INTO public.country (id, name) VALUES (574, 'Norfolk Island');
INSERT INTO public.country (id, name) VALUES (566, 'Nigeria');
INSERT INTO public.country (id, name) VALUES (558, 'Nicaragua');
INSERT INTO public.country (id, name) VALUES (570, 'Niue');
INSERT INTO public.country (id, name) VALUES (528, 'Netherlands');
INSERT INTO public.country (id, name) VALUES (578, 'Norway');
INSERT INTO public.country (id, name) VALUES (524, 'Nepal');
INSERT INTO public.country (id, name) VALUES (520, 'Nauru');
INSERT INTO public.country (id, name) VALUES (554, 'New Zealand');
INSERT INTO public.country (id, name) VALUES (512, 'Oman');
INSERT INTO public.country (id, name) VALUES (586, 'Pakistan');
INSERT INTO public.country (id, name) VALUES (591, 'Panama');
INSERT INTO public.country (id, name) VALUES (612, 'Pitcairn');
INSERT INTO public.country (id, name) VALUES (604, 'Peru');
INSERT INTO public.country (id, name) VALUES (608, 'Philippines');
INSERT INTO public.country (id, name) VALUES (585, 'Palau');
INSERT INTO public.country (id, name) VALUES (598, 'Papua New Guinea');
INSERT INTO public.country (id, name) VALUES (616, 'Poland');
INSERT INTO public.country (id, name) VALUES (630, 'Puerto Rico');
INSERT INTO public.country (id, name) VALUES (408, 'Korea, Democratic People''s Republic of');
INSERT INTO public.country (id, name) VALUES (620, 'Portugal');
INSERT INTO public.country (id, name) VALUES (600, 'Paraguay');
INSERT INTO public.country (id, name) VALUES (275, 'Palestine, State of');
INSERT INTO public.country (id, name) VALUES (258, 'French Polynesia');
INSERT INTO public.country (id, name) VALUES (634, 'Qatar');
INSERT INTO public.country (id, name) VALUES (638, 'Réunion');
INSERT INTO public.country (id, name) VALUES (642, 'Romania');
INSERT INTO public.country (id, name) VALUES (643, 'Russian Federation');
INSERT INTO public.country (id, name) VALUES (646, 'Rwanda');
INSERT INTO public.country (id, name) VALUES (682, 'Saudi Arabia');
INSERT INTO public.country (id, name) VALUES (729, 'Sudan');
INSERT INTO public.country (id, name) VALUES (686, 'Senegal');
INSERT INTO public.country (id, name) VALUES (702, 'Singapore');
INSERT INTO public.country (id, name) VALUES (239, 'South Georgia and the South Sandwich Islands');
INSERT INTO public.country (id, name) VALUES (654, 'Saint Helena, Ascension and Tristan da Cunha');
INSERT INTO public.country (id, name) VALUES (744, 'Svalbard and Jan Mayen');
INSERT INTO public.country (id, name) VALUES (90, 'Solomon Islands');
INSERT INTO public.country (id, name) VALUES (694, 'Sierra Leone');
INSERT INTO public.country (id, name) VALUES (222, 'El Salvador');
INSERT INTO public.country (id, name) VALUES (674, 'San Marino');
INSERT INTO public.country (id, name) VALUES (706, 'Somalia');
INSERT INTO public.country (id, name) VALUES (666, 'Saint Pierre and Miquelon');
INSERT INTO public.country (id, name) VALUES (688, 'Serbia');
INSERT INTO public.country (id, name) VALUES (728, 'South Sudan');
INSERT INTO public.country (id, name) VALUES (678, 'Sao Tome and Principe');
INSERT INTO public.country (id, name) VALUES (740, 'Suriname');
INSERT INTO public.country (id, name) VALUES (703, 'Slovakia');
INSERT INTO public.country (id, name) VALUES (705, 'Slovenia');
INSERT INTO public.country (id, name) VALUES (752, 'Sweden');
INSERT INTO public.country (id, name) VALUES (748, 'Eswatini');
INSERT INTO public.country (id, name) VALUES (534, 'Sint Maarten (Dutch part)');
INSERT INTO public.country (id, name) VALUES (690, 'Seychelles');
INSERT INTO public.country (id, name) VALUES (760, 'Syrian Arab Republic');
INSERT INTO public.country (id, name) VALUES (796, 'Turks and Caicos Islands');
INSERT INTO public.country (id, name) VALUES (148, 'Chad');
INSERT INTO public.country (id, name) VALUES (768, 'Togo');
INSERT INTO public.country (id, name) VALUES (764, 'Thailand');
INSERT INTO public.country (id, name) VALUES (762, 'Tajikistan');
INSERT INTO public.country (id, name) VALUES (772, 'Tokelau');
INSERT INTO public.country (id, name) VALUES (795, 'Turkmenistan');
INSERT INTO public.country (id, name) VALUES (626, 'Timor-Leste');
INSERT INTO public.country (id, name) VALUES (776, 'Tonga');
INSERT INTO public.country (id, name) VALUES (780, 'Trinidad and Tobago');
INSERT INTO public.country (id, name) VALUES (788, 'Tunisia');
INSERT INTO public.country (id, name) VALUES (792, 'Turkey');
INSERT INTO public.country (id, name) VALUES (798, 'Tuvalu');
INSERT INTO public.country (id, name) VALUES (158, 'Taiwan, Province of China');
INSERT INTO public.country (id, name) VALUES (834, 'Tanzania, United Republic of');
INSERT INTO public.country (id, name) VALUES (800, 'Uganda');
INSERT INTO public.country (id, name) VALUES (804, 'Ukraine');
INSERT INTO public.country (id, name) VALUES (581, 'United States Minor Outlying Islands');
INSERT INTO public.country (id, name) VALUES (858, 'Uruguay');
INSERT INTO public.country (id, name) VALUES (840, 'United States');
INSERT INTO public.country (id, name) VALUES (860, 'Uzbekistan');
INSERT INTO public.country (id, name) VALUES (336, 'Holy See (Vatican City State)');
INSERT INTO public.country (id, name) VALUES (670, 'Saint Vincent and the Grenadines');
INSERT INTO public.country (id, name) VALUES (862, 'Venezuela, Bolivarian Republic of');
INSERT INTO public.country (id, name) VALUES (92, 'Virgin Islands, British');
INSERT INTO public.country (id, name) VALUES (850, 'Virgin Islands, U.S.');
INSERT INTO public.country (id, name) VALUES (704, 'Viet Nam');
INSERT INTO public.country (id, name) VALUES (548, 'Vanuatu');
INSERT INTO public.country (id, name) VALUES (876, 'Wallis and Futuna');
INSERT INTO public.country (id, name) VALUES (882, 'Samoa');
INSERT INTO public.country (id, name) VALUES (887, 'Yemen');
INSERT INTO public.country (id, name) VALUES (710, 'South Africa');
INSERT INTO public.country (id, name) VALUES (894, 'Zambia');
INSERT INTO public.country (id, name) VALUES (716, 'Zimbabwe');